# Generated by Django 4.0.5 on 2022-06-18 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaTempo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now=True)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clima Tempo',
                'verbose_name_plural': 'Climas Tempo',
                'db_table': 'clima_tempo',
                'ordering': ['-created_at'],
                'permissions': (('view_climatempo', 'Can view clima_tempo'),),
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
