# Generated by Django 4.0.5 on 2022-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_region_num_region_weather_dt_alter_region_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='lon',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='num_region',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='population',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='sunrise',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='sunset',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='temp',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='timezone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='deg',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='dt',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='dt_txt',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='feels_like',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='icon',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='lat',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='lon',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='population',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='region_id',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='speed',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sunrise',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sunset',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_max',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_min',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='timezone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
