# Generated by Django 4.0.5 on 2022-06-18 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_alter_climatempo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidade',
                'ordering': ['-created_at'],
                'permissions': (('view_cidade', 'Can view cidade'),),
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
